//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calls
    {
        public int CallsId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public Nullable<int> CallContactId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
